#!/bin/bash

set -e

SITE=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
OUTDIR=_site

# Clear output directory
rm -rf $OUTDIR
mkdir -p $OUTDIR

# Install generator dependencies, if necessary
if [ ! -d $SITE/generate/node_modules ]; then
  ( cd $SITE/generate && npm install );
fi

# Use generator
node $SITE/generate $SITE $OUTDIR

# Make static directory
mkdir -p $OUTDIR/static

# Copy and minify css
cleancss --skip-rebase -o $OUTDIR/static/site.css \
  $SITE/assets/Skeleton-2.0.4/css/{normalize.css,skeleton.css} \
  $SITE/assets/font-awesome-4.3.0/css/font-awesome.css \
  $SITE/assets/site.css

# Copy js
cat $SITE/assets/site.js > $OUTDIR/static/site.js

# Copy fonts
cp -r $SITE/assets/font-awesome-4.3.0/fonts/ $OUTDIR/static
