#!/bin/bash

set -e
set -x

# Update all the things
apt-get update

# Add node ppa
curl -sL https://deb.nodesource.com/setup | bash -

# Install all the things
apt-get install -y git nginx nodejs

# Setup nginx
make -C /vagrant nginx-dev
