#!/bin/bash

set -e
set -x

# Update all the things
apt-get update

# Get node
curl -sL https://deb.nodesource.com/setup | bash -
apt-get -y install nodejs

# Get and configure nginx
apt-get install -y nginx

cat > /etc/nginx/sites-enabled/relevance <<EOF
server {
  listen 4000 default_server;
  server_name localhost;

  root /home/vagrant/output;

  location / {
    try_files \$uri \$uri/ =404;
  }
}
EOF

nginx -s reload
